#!/usr/bin/env bash
set -uo pipefail
# Download all 36 Spero-filtered publications from daylightsolutions.com
# Source filter: product = Spero (https://www.daylightsolutions.com/resources/scientific-research-papers/?_research_papers_products=spero)
# Run this on your machine (the sandbox cannot reach the CDN). PDFs land next to this script.
cd "$(dirname "$0")"
fail=0

echo "[01/36] 01_2017_3d-chemical-imaging-of-the-brain-by-quantitative.pdf"
curl -fSL --retry 3 --retry-delay 2 -o "01_2017_3d-chemical-imaging-of-the-brain-by-quantitative.pdf" "https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2017/10/2017-Petibois-et-al-Chemical-Science.pdf" || { echo "  FAILED: https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2017/10/2017-Petibois-et-al-Chemical-Science.pdf"; fail=$((fail+1)); }
echo "[02/36] 02_2017_3d-quantitative-chemical-imaging-of-tissues-by-spectromics.pdf"
curl -fSL --retry 3 --retry-delay 2 -o "02_2017_3d-quantitative-chemical-imaging-of-tissues-by-spectromics.pdf" "https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2017/10/1-s2.0-S0167779917302068-main.pdf" || { echo "  FAILED: https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2017/10/1-s2.0-S0167779917302068-main.pdf"; fail=$((fail+1)); }
echo "[03/36] 03_2023_a-framework-for-falsifiable-explanations-of-machine-learning.pdf"
curl -fSL --retry 3 --retry-delay 2 -o "03_2023_a-framework-for-falsifiable-explanations-of-machine-learning.pdf" "https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2023/01/2023-A-framework-for-falsifiable-explanations-of-machine-learning-models-with-an-application-in-computational-pathology.pdf" || { echo "  FAILED: https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2023/01/2023-A-framework-for-falsifiable-explanations-of-machine-learning-models-with-an-application-in-computational-pathology.pdf"; fail=$((fail+1)); }
echo "[04/36] 04_2026_a-functional-amyloid-matrix-underpins-the-pdim-architected.pdf"
curl -fSL --retry 3 --retry-delay 2 -o "04_2026_a-functional-amyloid-matrix-underpins-the-pdim-architected.pdf" "https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2026/05/functional-amyloid-matrix-underpins.pdf" || { echo "  FAILED: https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2026/05/functional-amyloid-matrix-underpins.pdf"; fail=$((fail+1)); }
echo "[05/36] 05_2016_a-protocol-for-rapid-label-free-histochemical-imaging.pdf"
curl -fSL --retry 3 --retry-delay 2 -o "05_2016_a-protocol-for-rapid-label-free-histochemical-imaging.pdf" "https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2018/04/2016_Analyst_Bird_A-protocol-for-liver-fibrosis-1.pdf" || { echo "  FAILED: https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2018/04/2016_Analyst_Bird_A-protocol-for-liver-fibrosis-1.pdf"; fail=$((fail+1)); }
echo "[06/36] 06_2026_an-ir-transparent-ewod-digital-microfluidic-platform-for.pdf"
curl -fSL --retry 3 --retry-delay 2 -o "06_2026_an-ir-transparent-ewod-digital-microfluidic-platform-for.pdf" "https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2026/05/ir-transparent-ewod-digital-microfluidic-platfom.pdf" || { echo "  FAILED: https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2026/05/ir-transparent-ewod-digital-microfluidic-platfom.pdf"; fail=$((fail+1)); }
echo "[07/36] 07_2018_denoising-influence-on-discrete-frequency-classification-results-for.pdf"
curl -fSL --retry 3 --retry-delay 2 -o "07_2018_denoising-influence-on-discrete-frequency-classification-results-for.pdf" "https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2018/12/Denoising-influence-on-discrete-frequency-classification-results-for-quantum-cascade-laser-based-infrared-microscopy-Abstract.pdf" || { echo "  FAILED: https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2018/12/Denoising-influence-on-discrete-frequency-classification-results-for-quantum-cascade-laser-based-infrared-microscopy-Abstract.pdf"; fail=$((fail+1)); }
echo "[08/36] 08_2017_development-of-a-robust-and-reusable-microreactor-employing.pdf"
curl -fSL --retry 3 --retry-delay 2 -o "08_2017_development-of-a-robust-and-reusable-microreactor-employing.pdf" "https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2020/07/2017-KelesGSK-Organic-Process-Research-and-Development.pdf" || { echo "  FAILED: https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2020/07/2017-KelesGSK-Organic-Process-Research-and-Development.pdf"; fail=$((fail+1)); }
echo "[09/36] 09_2023_fast-and-label-free-automated-detection-of-microsatellite.pdf"
curl -fSL --retry 3 --retry-delay 2 -o "09_2023_fast-and-label-free-automated-detection-of-microsatellite.pdf" "https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2023/03/2023-label-free-automated-detection-of-microsatellite_stable-Artificicial-Intelligence_Gerwert_Schorner_Tannapfel.pdf" || { echo "  FAILED: https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2023/03/2023-label-free-automated-detection-of-microsatellite_stable-Artificicial-Intelligence_Gerwert_Schorner_Tannapfel.pdf"; fail=$((fail+1)); }
echo "[10/36] 10_2017_fourier-transform-vs-quantum-cascade-laser-infrared-microscopes.pdf"
curl -fSL --retry 3 --retry-delay 2 -o "10_2017_fourier-transform-vs-quantum-cascade-laser-infrared-microscopes.pdf" "https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2018/04/Ogunleke-et-al.-TrAC-2017-in-press.pdf" || { echo "  FAILED: https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2018/04/Ogunleke-et-al.-TrAC-2017-in-press.pdf"; fail=$((fail+1)); }
echo "[11/36] 11_2017_high-definition-infrared-chemical-imaging-of-colorectal-tissue.pdf"
curl -fSL --retry 3 --retry-delay 2 -o "11_2017_high-definition-infrared-chemical-imaging-of-colorectal-tissue.pdf" "https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2018/04/2017_Analyst_Bird_SperoHighDefColon.pdf" || { echo "  FAILED: https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2018/04/2017_Analyst_Bird_SperoHighDefColon.pdf"; fail=$((fail+1)); }
echo "[12/36] 12_2017_high-confidence-high-throughput-screening-with-high-def.pdf"
curl -fSL --retry 3 --retry-delay 2 -o "12_2017_high-confidence-high-throughput-screening-with-high-def.pdf" "https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2017/09/Daylight-BioOptics-laser-based-IR-Microscope-Spero.pdf" || { echo "  FAILED: https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2017/09/Daylight-BioOptics-laser-based-IR-Microscope-Spero.pdf"; fail=$((fail+1)); }
echo "[13/36] 13_2016_high-throughput-quantum-cascade-laser-qcl-spectral-histopathology.pdf"
curl -fSL --retry 3 --retry-delay 2 -o "13_2016_high-throughput-quantum-cascade-laser-qcl-spectral-histopathology.pdf" "https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2018/04/Gardner-et-al-RSC-Faraday-Discussion.pdf" || { echo "  FAILED: https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2018/04/Gardner-et-al-RSC-Faraday-Discussion.pdf"; fail=$((fail+1)); }
echo "[14/36] 14_2022_imaging-3d-molecular-orientation-by-orthogonal-pair-polarization.pdf"
curl -fSL --retry 3 --retry-delay 2 -o "14_2022_imaging-3d-molecular-orientation-by-orthogonal-pair-polarization.pdf" "https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2022/03/2022-Imaging-3D-molecular-orientation-by-orthogonal-pair-polarization-IR-microscopy.pdf" || { echo "  FAILED: https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2022/03/2022-Imaging-3D-molecular-orientation-by-orthogonal-pair-polarization-IR-microscopy.pdf"; fail=$((fail+1)); }
echo "[15/36] 15_2018_imaging-based-molecular-barcoding-with-pixelated-dielectric-metasurfaces.pdf"
curl -fSL --retry 3 --retry-delay 2 -o "15_2018_imaging-based-molecular-barcoding-with-pixelated-dielectric-metasurfaces.pdf" "https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2018/06/Imaging-based-molecular-barcoding-with-pixelated-dielectric-metasurfaces-Abstract.pdf" || { echo "  FAILED: https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2018/06/Imaging-based-molecular-barcoding-with-pixelated-dielectric-metasurfaces-Abstract.pdf"; fail=$((fail+1)); }
echo "[16/36] 16_2017_infrared-spectroscopic-imaging-detects-chemical-modifications-in-liver.pdf"
curl -fSL --retry 3 --retry-delay 2 -o "16_2017_infrared-spectroscopic-imaging-detects-chemical-modifications-in-liver.pdf" "https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2017/09/Spero-Walsh-liver-fibrosis.pdf" || { echo "  FAILED: https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2017/09/Spero-Walsh-liver-fibrosis.pdf"; fail=$((fail+1)); }
echo "[17/36] 17_2017_introducing-discrete-frequency-infrared-technology-for-high-throughput.pdf"
curl -fSL --retry 3 --retry-delay 2 -o "17_2017_introducing-discrete-frequency-infrared-technology-for-high-throughput.pdf" "https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2017/09/Baker-Daylight-Spero-Discrete-Frequency-IR-for-biofluid.pdf" || { echo "  FAILED: https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2017/09/Baker-Daylight-Spero-Discrete-Frequency-IR-for-biofluid.pdf"; fail=$((fail+1)); }
echo "[18/36] 18_2023_label-free-analytic-histology-of-carotid-atherosclerosis-by.pdf"
curl -fSL --retry 3 --retry-delay 2 -o "18_2023_label-free-analytic-histology-of-carotid-atherosclerosis-by.pdf" "https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2023/03/2023-Label-free-analytic-histology-of-carotid-atherosclerosis-by-mid-infrared-optoacoustic-microscopy.pdf" || { echo "  FAILED: https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2023/03/2023-Label-free-analytic-histology-of-carotid-atherosclerosis-by-mid-infrared-optoacoustic-microscopy.pdf"; fail=$((fail+1)); }
echo "[19/36] 19_2025_label-free-abeta-plaque-detection-in-alzheimer-s.pdf"
curl -fSL --retry 3 --retry-delay 2 -o "19_2025_label-free-abeta-plaque-detection-in-alzheimer-s.pdf" "https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2025/03/Muller_Groseruschkamp_Gerwert_label-free-Abeta-plaque-detection-i9n-Alzheimerss-deseae-brain-tissue.pdf" || { echo "  FAILED: https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2025/03/Muller_Groseruschkamp_Gerwert_label-free-Abeta-plaque-detection-i9n-Alzheimerss-deseae-brain-tissue.pdf"; fail=$((fail+1)); }
echo "[20/36] 20_2017_label-free-molecular-imaging-of-the-kidney.pdf"
curl -fSL --retry 3 --retry-delay 2 -o "20_2017_label-free-molecular-imaging-of-the-kidney.pdf" "https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2017/08/Label-free-molecular-imaging-of-the-kidney.pdf" || { echo "  FAILED: https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2017/08/Label-free-molecular-imaging-of-the-kidney.pdf"; fail=$((fail+1)); }
echo "[21/36] 21_2020_label-free-automated-classification-of-microsatellite-status-in.pdf"
curl -fSL --retry 3 --retry-delay 2 -o "21_2020_label-free-automated-classification-of-microsatellite-status-in.pdf" "https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2020/07/20200623_Gerwert_Colon_Cancer-Microsatellite_stable_s41598-020-67052-z-003.pdf" || { echo "  FAILED: https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2020/07/20200623_Gerwert_Colon_Cancer-Microsatellite_stable_s41598-020-67052-z-003.pdf"; fail=$((fail+1)); }
echo "[22/36] 22_2017_large-scale-imaging-of-tissue-micro-arrays-tmas.pdf"
curl -fSL --retry 3 --retry-delay 2 -o "22_2017_large-scale-imaging-of-tissue-micro-arrays-tmas.pdf" "https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2017/09/Spero-TMA-Imaging-with-Spero-Gardner-22May14.pdf" || { echo "  FAILED: https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2017/09/Spero-TMA-Imaging-with-Spero-Gardner-22May14.pdf"; fail=$((fail+1)); }
echo "[23/36] 23_2020_mid-infrared-metabolic-imaging-with-vibrational-probes.pdf"
curl -fSL --retry 3 --retry-delay 2 -o "23_2020_mid-infrared-metabolic-imaging-with-vibrational-probes.pdf" "https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2020/07/Mid-infrared-metabolic-imaging-with-vibrational-probes.pdf" || { echo "  FAILED: https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2020/07/Mid-infrared-metabolic-imaging-with-vibrational-probes.pdf"; fail=$((fail+1)); }
echo "[24/36] 24_2019_molecular-contrast-on-phase-contrast-microscopes.pdf"
curl -fSL --retry 3 --retry-delay 2 -o "24_2019_molecular-contrast-on-phase-contrast-microscopes.pdf" "https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2020/01/Molecular-contrast-on-phase-contrast-microscopes.pdf" || { echo "  FAILED: https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2020/01/Molecular-contrast-on-phase-contrast-microscopes.pdf"; fail=$((fail+1)); }
echo "[25/36] 25_2017_new-source-improves-infrared-imaging.pdf"
curl -fSL --retry 3 --retry-delay 2 -o "25_2017_new-source-improves-infrared-imaging.pdf" "https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2017/09/Spero-CE-News-QCL_Sources-2015JAN05.pdf" || { echo "  FAILED: https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2017/09/Spero-CE-News-QCL_Sources-2015JAN05.pdf"; fail=$((fail+1)); }
echo "[26/36] 26_2018_predicting-fibrosis-progression-in-renal-transplant-recipients-using.pdf"
curl -fSL --retry 3 --retry-delay 2 -o "26_2018_predicting-fibrosis-progression-in-renal-transplant-recipients-using.pdf" "https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2018/03/Predicting-Fibrosis-Progression-in-Renal-Transplant-Recipients-Using-Laser-Based-Infrared-Spectroscopic-Imaging.pdf" || { echo "  FAILED: https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2018/03/Predicting-Fibrosis-Progression-in-Renal-Transplant-Recipients-Using-Laser-Based-Infrared-Spectroscopic-Imaging.pdf"; fail=$((fail+1)); }
echo "[27/36] 27_2023_probing-the-micro-and-nanoscopic-properties-of-dental.pdf"
curl -fSL --retry 3 --retry-delay 2 -o "27_2023_probing-the-micro-and-nanoscopic-properties-of-dental.pdf" "https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2023/05/Probing-the-micro-and-nanoscopic-properties-of-dental-materials-using-infrared.pdf" || { echo "  FAILED: https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2023/05/Probing-the-micro-and-nanoscopic-properties-of-dental-materials-using-infrared.pdf"; fail=$((fail+1)); }
echo "[28/36] 28_2021_qcl-based-mid-infrared-hyperspectral-imaging-of-multilayer.pdf"
curl -fSL --retry 3 --retry-delay 2 -o "28_2021_qcl-based-mid-infrared-hyperspectral-imaging-of-multilayer.pdf" "https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2021/04/2021-QCL-based-mid-infrared-hyperspectral-imaging-of-multilayer-polymer-oxygen-barrier-films.pdf" || { echo "  FAILED: https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2021/04/2021-QCL-based-mid-infrared-hyperspectral-imaging-of-multilayer-polymer-oxygen-barrier-films.pdf"; fail=$((fail+1)); }
echo "[29/36] 29_2017_quantum-cascade-laser-spectral-histopathology-breast-cancer-diagnostics.pdf"
curl -fSL --retry 3 --retry-delay 2 -o "29_2017_quantum-cascade-laser-spectral-histopathology-breast-cancer-diagnostics.pdf" "https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2017/08/2017QuantumCascadeLaserSpectralHistopathology-BreastCancerDiagnosticsUsingHighThroughputChemicalImaging.pdf" || { echo "  FAILED: https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2017/08/2017QuantumCascadeLaserSpectralHistopathology-BreastCancerDiagnosticsUsingHighThroughputChemicalImaging.pdf"; fail=$((fail+1)); }
echo "[30/36] 30_2021_quantum-cascade-laser-based-infrared-imaging-as-a.pdf"
curl -fSL --retry 3 --retry-delay 2 -o "30_2021_quantum-cascade-laser-based-infrared-imaging-as-a.pdf" "https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2021/06/2021-Quantum-Cascade-Laser-Based-Infrared-Imaging-as-a-Label-Free-and-Automated-Approach-to-Determine-Mutations-in-Lung-Adenocarcinoma.pdf" || { echo "  FAILED: https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2021/06/2021-Quantum-Cascade-Laser-Based-Infrared-Imaging-as-a-Label-Free-and-Automated-Approach-to-Determine-Mutations-in-Lung-Adenocarcinoma.pdf"; fail=$((fail+1)); }
echo "[31/36] 31_2018_quantum-cascade-laser-based-infrared-microscopy-for-label.pdf"
curl -fSL --retry 3 --retry-delay 2 -o "31_2018_quantum-cascade-laser-based-infrared-microscopy-for-label.pdf" "https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2018/05/2018-Quantum-Cascade-Laser-Based-Infrared-Microscopy-for-Label-Free-and-Automated-Cancer-Classification-in-Tissue-Sections.pdf" || { echo "  FAILED: https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2018/05/2018-Quantum-Cascade-Laser-Based-Infrared-Microscopy-for-Label-Free-and-Automated-Cancer-Classification-in-Tissue-Sections.pdf"; fail=$((fail+1)); }
echo "[32/36] 32_2017_quantum-cascade-laser-based-mid-infrared-spectrochemical-imaging.pdf"
curl -fSL --retry 3 --retry-delay 2 -o "32_2017_quantum-cascade-laser-based-mid-infrared-spectrochemical-imaging.pdf" "https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2017/09/Spero-imaging-of-tissue-and-biofluids-Baker.pdf" || { echo "  FAILED: https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2017/09/Spero-imaging-of-tissue-and-biofluids-Baker.pdf"; fail=$((fail+1)); }
echo "[33/36] 33_2020_rapid-identification-and-quantification-of-microplastics-in-the.pdf"
curl -fSL --retry 3 --retry-delay 2 -o "33_2020_rapid-identification-and-quantification-of-microplastics-in-the.pdf" "https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2020/12/primpke-et-al-2020-rapid-identification-and-quantification-of-microplastics-in-the-environment-by-quantum-cascade-laser.pdf" || { echo "  FAILED: https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2020/12/primpke-et-al-2020-rapid-identification-and-quantification-of-microplastics-in-the-environment-by-quantum-cascade-laser.pdf"; fail=$((fail+1)); }
echo "[34/36] 34_2017_real-time-mid-ir-chemical-imaging-of-dynamic.pdf"
curl -fSL --retry 3 --retry-delay 2 -o "34_2017_real-time-mid-ir-chemical-imaging-of-dynamic.pdf" "https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2017/09/Spero-AN201501-Real-Time-Chemical-Imaging-of-Microfluidic-System.pdf" || { echo "  FAILED: https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2017/09/Spero-AN201501-Real-Time-Chemical-Imaging-of-Microfluidic-System.pdf"; fail=$((fail+1)); }
echo "[35/36] 35_2026_small-microplastics-and-microfibers-found-in-high-concentrations.pdf"
curl -fSL --retry 3 --retry-delay 2 -o "35_2026_small-microplastics-and-microfibers-found-in-high-concentrations.pdf" "https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2026/06/1-s2.0-S2666765726000293-main.pdf" || { echo "  FAILED: https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2026/06/1-s2.0-S2666765726000293-main.pdf"; fail=$((fail+1)); }
echo "[36/36] 36_2022_three-dimensional-molecular-orientation-imaging-of-a-semicrystalline.pdf"
curl -fSL --retry 3 --retry-delay 2 -o "36_2022_three-dimensional-molecular-orientation-imaging-of-a-semicrystalline.pdf" "https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2022/03/2022-Three-Dimensional-Molecular-Orientation-Imaging-of-a-Semicrystalline-Polymer-Film-under-Shear-Deformation.pdf" || { echo "  FAILED: https://cdn.leonardodrs.com/uploads/wp-content/uploads/sites/3/2022/03/2022-Three-Dimensional-Molecular-Orientation-Imaging-of-a-Semicrystalline-Polymer-Film-under-Shear-Deformation.pdf"; fail=$((fail+1)); }

echo "----"
echo "PDFs present: $(ls -1 *.pdf 2>/dev/null | wc -l) / 36   failures: $fail"
